version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://server:3001
    depends_on:
      - server
    networks:
      - space-mission-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server/uploads:/app/uploads
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - space-mission-network

networks:
  space-mission-network:
    driver: bridge 